#lang racket

#|
Exercise 1.14.
Draw the tree illustrating the process generated by the count-change procedure
of section 1.2.2 in making change for 11 cents. What are the orders of growth
of the space and number of steps used by this process as the amount to be
changed increases?
|#
(define (count-change amount)
  (cc amount 5))
(define (cc amount kinds-of-coins)
  (cond ((= amount 0) 1)
        ((or (< amount 0) (= kinds-of-coins 0)) 0)
        (else (+ (cc amount
                     (- kinds-of-coins 1))
                 (cc (- amount
                        (first-denomination kinds-of-coins))
                     kinds-of-coins)))))
(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))

(count-change 100)
;292

#|
                                                    11 5
                                                 /         \
                                              11 4       -39 5 (0)
                                              /    \
                                            11 3   -14 4 (0)
                                        /      \
                                      11 2       - - - - - - - - - 1 3
                                   /       \                     /      \
                                    11 1     6 2               1 2      -9 3
                                   /   |       |  \            |  \        \
                                 (0) 10 1     6 1  1 1        1 1  -4 2     (0)
                                    /   |    /  |  |  \        |  \    \
                                  (0)  9 1 (0) 5 1 (0) (1)    (0) (1)  (0)
                                       / \     / \
                                     (0) 8 1  (0) 4 1
                                        / |       |  \
                                      (0) 7 1    (0)  3 1
                                         / |         /   \
                                       (0) 6 1      (0)  2 1
                                          /  \          /   \
                                        (0)  5 1      (0)   1 1
                                            /  \           /   \
                                          (0)   4 1      (0)   (1)
                                               /   \
                                             (0)   3 1
                                                  /   \
                                                (0)   2 1
                                                     /   \
                                                   (0)   1 1
                                                        /   \
                                                      (0)   (1)

Answer 4

Number of Steps is O(n^2)
Space taken is O(n)

|#
